# This is a basic workflow to help you get started with Actions

name: Nuget Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.403
    - name: Install dependencies
      run: dotnet restore SerialPortService.sln
      
    - name: Build
      run: dotnet build SerialPortService.sln --configuration Release --no-restore 
      
    - name: Publish Nuget Packet
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: SerialPortService/SerialPortService.csproj
          NUGET_KEY: ${{secrets.Nuget_API_Token}}
